### ISSUE TITLE
TOR as VPN Option

### ISSUE THREAD

**Issue by ryanleesipes** [system76/pop-distro#13]
**Feature Request**

I think to offer TOR as an OOTB VPN option in the networking/privacy settings would be really powerful and a great differentiator. With a focus on encryption already with the distribution, this would allow us to set Pop apart as a leader in privacy and security. I know that some people have set up [transparent proxies in the past to accomplish this](http://www.digitalarmedforces.org/index.php/8-linux/19-how-to-setup-tor-as-a-transparent-proxy-on-ubuntu-linux), I'm not really certain as to what the best way to accomplish this now is.

**Comment by isantop** [comment]
Doing this is tricky, because it's very difficult to enforce a proxy setting for the entire system (Some apps ignore the system privacy/proxy settings). It's also important to note that it isn't a _VPN_ but a _proxy_ and using TOR doesn't guarantee a wide degree of security or anonymity. With the proper disclaimers it could probably work.

**Comment by ryanleesipes** [comment]
Yeah, obviously it shouldn't be intended to be a complete privacy catch-all. But I love my VPN option in the drop down (show below). Would love a one-click TOR proxy option (for the privacy conscious). Disclaimers are acceptable, given this is an advanced user option.
![screenshot from 2017-06-27 15-48-04](https://user-images.githubusercontent.com/2141621/27611638-2f075814-5b50-11e7-826d-fff90c72adac.png)

**Comment by WatchMkr** [comment]
Please discuss feature request at our Pop!_OS subreddit.

https://www.reddit.com/r/pop_os/
