### ISSUE TITLE
Clarify the scope of the project

### ISSUE THREAD

**Issue by jimsalterjrs** [system76/pop-distro#19]
Pop!_OS is being reported on Reddit and Phoronix as a "distro".  And the name of the project here on GitHub is "pop-distro".  But the README refers to it as a spin.

It would be helpful to clarify the scope and aim of the project, as well as how much interoperability should be expected with mainline Ubuntu, and whether (and/or how much) Pop!_OS will be supported on non-System76 hardware.

Thank you.

**Comment by davidak** [comment]
My first thought regarding this distro was: "Why another distro?"

You should really collaborate with Ubuntu or @elementary to improve their distro.

When your distro adds custom themes or apps, push them upstream and write a tutorial how one uses them.

When your distro ist just a collection of software for creatives, provide a list of good software with instruction how to install them on Ubuntu/elementary OS and maybe a one-liner to install them all.

Linux has a market share of <5%, we must collaborate to create a serious alternative!

**Comment by WatchMkr** [comment]
I completely disagree with the idea that we shouldn't make a distro. A vibrant and successful collection of anything has substantial diversification. The more the better. Should all music be Country and Rock genres because artist not conforming are diluting the Country and Rock pool in some way? Of course not. Go make music! Make what you love. Do what you're good at. 

The more distros we have, with more specialization and more testing of ideas, the more successful Linux will be. Proprietary software can't compete with this. It's impossible for them.

We disparage monopolies but say they should exist in our own community. That we should consolidate. Consolidation is the beginning of monopolies and the reduction of choice for the consumer.

The idea that there should be no more distros, that everything is as it should be, is fundamentally wrong and counter to the ideals of open source.

**Comment by davidak** [comment]
@WatchMkr i don't say we should have only one Linux OS and i don't say you shouldn't create a distro that tries something new, but i ask the question "Why invest time to create Pop! OS instead of a tutorial to achieve the same with Ubuntu?" And i'm ok if you have a good reason, i don't know the project and it seams to be just another Ubuntu derivate with software for creatives pre installed. The effort maintaining such a project is huge when you do it right and at the same time, Ubuntu has still issues.

I don't like the situation that i can't recommend Linux to a normal person in 2017. I use elementary OS on a MacBook Pro (at work) and have huge issues, like wifi don't works with newer kernels, so i'm stuck with one kernel version. That is a issue of Ubuntu. https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1681904

If we want to have a "year of the linux desktop" before desktops are obsolete, we should focus on making linux more accessible for everage people. System76 and Ubuntu do a great job here.

**Comment by WatchMkr** [comment]
> I use elementary OS on a MacBook Pro (at work) and have huge issues, like wifi don't works with newer kernels, so i'm stuck with one kernel version. 

That's an issue with Mac and a large part of why we're here. Those problems don't occur on our products - or if they do - there's a support and engineering team there to resolve the problem.

> If we want to have a "year of the linux desktop" before desktops are obsolete, we should focus on making linux more accessible for average people. System76 and Ubuntu do a great job here.

This is the point. This is why we're making a distribution. Our goals are different. We're not trying to make it the year of the Linux desktop. Our goal is to make the best tool for our customers.

**Comment by Ads20000** [comment]
'Our goal is to make the best tool for our customers.' And default Ubuntu with GNOME won't do this because...?
As long as you contribute as much as possible back to Ubuntu, Debian, and GNOME, just as Ubuntu tries to contribute as much as possible back to Debian and GNOME, then, I guess, fair enough, everyone wins!

**Comment by WatchMkr** [comment]
Sorry, I let this one get out of hand. Let's clear it up.

> Pop!_OS is being reported on Reddit and Phoronix as a "distro". And the name of the project here on GitHub is "pop-distro". But the README refers to it as a spin.

It is a distro. There's going to be a good deal of documentation production and refinement as we reach release.

> It would be helpful to clarify the scope and aim of the project, as well as how much interoperability should be expected with mainline Ubuntu

The target audience for this distribution are people that use their computer to create things - particularly in computer science. Our research, user testing, and engineering will be guided by the principle of helping those users be more productive.

>  And whether (and/or how much) Pop!_OS will be supported on non-System76 hardware.

Pop!_OS will work on other hardware. It is guaranteed to work on System76 hardware. This is the same as Ubuntu today. Commercial support comes with System76 hardware.

Great questions! Thanks!
