### ISSUE TITLE
Feature Request: Install and activate Synapse by default

### ISSUE THREAD

**Issue by jlacroix82** [system76/pop-distro#22]
Feature request: Install Synapse by default and have it automatically come up at boot. This allows you to launch applications and open files quickly, by pressing CTRL+Space, you can bring up a menu to search content faster than the GNOME shell.

**Comment by haevalencia** [comment]
This is somewhat counterproductive and totally optional, since gnome-shell has its own launcher that is powerful and well-integrated, using [tracker search engine](https://wiki.gnome.org/Projects/Tracker) power. Adding an additional service -zeitgeist- that performs a similar task to what is available makes no sense to me IMO. I think devs have to take advantage of what gnome offers by default and take advantage of it, even an extension can improve the run dialog if you want more functionality to something similar to how the budgie run dialog works.

![](https://solus-project.com/imgs/posts//2017/04/Budgie_RunDialog.jpg)

**Comment by ryanleesipes** [comment]
Two things, one is @haevalencia what extension were you referencing?

Two, as per the [contribution guidelines](https://github.com/system76/pop-distro/blob/master/CONTRIBUTING.md), let's move this discussion to the [Pop!_Subreddit](https://reddit.com/r/pop_os).
