### ISSUE TITLE
Install a restore partition by default

### ISSUE THREAD

**Issue by ChloeWolfieGirl** [system76/pop-distro#37]
With Steam OS if something breaks there's an option at boot to boot a different partition which will fix the operating system without having to do a complete reinstall, and keeps your data intact.

**Comment by cameronaaron** [comment]
In addition, I also recommend some sort of a Full Hardware Diagnostic option in this mode. That can identify problemed hardware and do a CPU stress test to see if it fails under high load

**Comment by ryanleesipes** [comment]
This is something we need to discuss at some length methinks in order to determine if it has merit. Following the [development approach](http://pop.system76.com/docs/pop-os-development-approach/) and [contribution guidelines](https://github.com/system76/pop-distro/blob/master/CONTRIBUTING.md), we should have this conversation over on the [Pop!_Subreddit](https://reddit.com/r/pop_os).
