### ISSUE TITLE
How to minimize windows?

### ISSUE THREAD

**Issue by huyndnse63331** [system76/pop-distro#38]
There's only close windows button, no option for minimizing

**Comment by TheMonologueGuy** [comment]
Not sure if Gnome has that option. My workaround has been the 'desktop from
overview' extension.

**Comment by ggarndt2** [comment]
Have to open gnome tweak tool and then open extensions window.   Near bottom, one of the categories (maybe "windows") provides check butttons for enabling min and max.     Get familiar with the tweak tool and extensions (be sure to add "Dash to Dock") . . . otherwise gnome not especially user friendly imho.

**Comment by ryanleesipes** [comment]
This is part of the GNOME desktop paradigm. This could be a conversation on the [Pop!_OS subreddit](https://reddit.com/r/pop_os) - as that is where we are discussing possible changes like that and having general discussion, as per the [CONTRIBUTING guidelines](https://github.com/system76/pop-distro/blob/master/CONTRIBUTING.md).
