### ISSUE TITLE
Need a Default Email Client

### ISSUE THREAD

**Issue by TheMonologueGuy** [system76/pop-distro#41]
**Reporter info**
TheMonologueGuy
```
 * Distribution - Pop OS 17.04
 * Related Application and/or Package Version - email client
```

**Actual issue**
There appears to be no preloaded email client for Pop. It might be beneficial to include one that can easily integrate with the Online Accounts step during initial setup.

**Other Note (feature-request, question, etc...)**
I typically use Thunderbird, however Geary's looking quite nice in Pop.

**Comment by michaldybczak** [comment]
I tested various email programs and... I decided to stick with Thunderbird, because rest is nowhere near its quality and possibilities. Sure, Thunderbird looks outdated and I love modern UI but in this case, I prefer functionality. Thunderbird simply does its job well. It's easy to configure email accounts because the process is automated and in 90% correct. It has a lot of great extensions, nice filtering features, it's perfect for business. I can easily transfer all my accounts and settings from one installation to another.

I'm afraid Pop will try to use some modern, another app for an email client because this is so trendy and Thunderbird is so boring choice. Yeah, boring but still THE BEST.

**Comment by TheMonologueGuy** [comment]
Agreed. Like I said, I typically go with Thunderbird because it's always
been the most reliable and robust. I tried Geary because it looked more
modern, but I was missing Thunderbird. If System76 does go with
Thunderbird, maybe they can give it a fresh coat of Pop paint.

**Comment by ryanleesipes** [comment]
Whatever we use will need to tie into GNOME online accounts and other applications like GNOME Calendar and Contacts. I know that other folks are looking into this (like elementary OS with Pantheon Mail).

This should be a higher priority of the project leading up to 17.10

**Comment by michaldybczak** [comment]
Thanks for info, however, that's a bit pity, because although such integration is great, it doesn't beat functionality. Gnome/elementary distro developers beat that drum and put those weird apps and do you see many people using them? Browser and mailapp are just bad, no matter how good looking and well integrated into DE. Music app or video apps are different beasts thou and there is less resistance to use default ones. Browsers and mail programs are too personal and people use too many of their features having strong habits.

This is a puzzle because at one side you will be judged by the look and consistency by people who just glance over the surface, while users will have their own preferences and most likely won't be on the same page. There is a reason why distros who aim at functionality are most popular and used, while distros that are distinctive and look good or interesting have a good press but users... love them less.

Everybody tries to create their own mac os ;). That's too huge temptation and using plain Thunderbird feels in opposite direction. Unfortunately, I haven't seen any worthy, modern, good looking, DE integrated mail app, maybe because those are huge and complex programs so only top dogs and pro apps are truly usable - Thunderbird belongs to that group. Geary, Kmail and others are just weak, good looking wannabes.

Well, we'll see how it goes. Now that Ubuntu is none essential player anymore (is not standing out), pop can be a good alternative, since Ubuntu foundation is a good one (although I personally don't use it, but I started with it and I respect it).

Good luck.

**Comment by ryanleesipes** [comment]
@michaldybczak it doesn't mean that you can't use Thunderbird, just that it won't be the default likely. Why not work on feature-parity with a client that ties into the desktop and feels completely native? While still using Thunderbird under you feel feature-parity is met?

**Comment by michaldybczak** [comment]
Well, if those mail programs will develop to a point when they reach Thunderbird level, then yes. I guess we can give them a chance, although it will be at least years in the feature.

It's like with elementary. People are praising its looks and consistency but first thing users do after installing is just getting their favorite programs that completely break that homogenous look. Those native apps are just like examples that you can advertise your distro with but are never really usable. The same like Wordpad or Paint. They never reached the level of the real stuff.

Anyway, you would never satisfy everyone ;P. Ship Pop! with Geary, people will complain that's not as good as it should be, ship with Thunderbird, you get criticized by populist, boring choice that doesn't fit the general UI feel.

**Comment by doctormo** [comment]
I've never understood why Thunderbird is the default. Every time I've tried it, it's just a huge Microsoft Outlook clone. And just like Firefox, it lacks Linux integration in a profound way. But maybe I expect more from my email app.

I use evolution at the moment, although it's got many problems and wouldn't recommend it.

I don't think there is an email application you should ship. Put pressure on developers to actually make a Linux desktop email application with some very specific list of features and integrations. It's not just looking nice, it's being nice too.

**Comment by michaldybczak** [comment]
Why? For starters:

- it's not from Microsoft, it's opensource
- it has THE BEST email account setting process from EVERY email client I ever met, you just give email, Thunderbird proposes default settings that are 80-90% right, if not, you can easily correct it at that stage, click next and everything runs!
- it works! Believe me or not, all other email clients have major issues with certain accounts for no reason, the same settings and yet Thunderbird works, others don't
- classic UI is simple and intuitive, all works as expected and is in place you would expect it, well, almost all, Thunderbird is not without issues, but in overall, it's worth it,
- it's great if you have many various email accounts - it offers a good overview and quick access to it
- it has AWESOME AND NECESSARY quick filtering and tagging options so you can easily quick search for unread, tagged, starred, with a certain phrase in a topic, message or whatnot
- it has A LOT OF OPTIONS, so you can customize it pretty well and if that's not enough:
- it has A LOT OF PLUGINS
- it's easy to copy all account settings from one system/computer to another, which is also crucial, you won't waste time setting those dozens of work accounts, again and again, just copy folder with settings on USB and copy it to current installation and all works like on an old computer, including plugins.

Seriously, none of the other clients offered me that, even paid ones were worse. I do need all of those. Once you get use to them, THERE IS NO REAL COMPETITION.

There is THUNDERBIRD as nr 1 and loooooong nothing and then on 50th place or so there are others.

**Comment by doctormo** [comment]
It sounds like you have a lot of yelling based opinions. -1

**Comment by RicardoEPRodrigues** [comment]
I have to praise Evolution for using Online Accounts and being so well integrated with the system.

Maybe the solution would be to strip down Evolution to a mail client instead of a all in one thing.

**Comment by kawaii** [comment]
I use Tunderbird as my daily driver, it does everything that I need it to but I feel that it does indeed have a dated UI. I have no idea if it supports theming/skinning but if it didn't I suppose an option is to fork it, alter the appearance and then just merge updates and patches from the upstream?

**Comment by michaldybczak** [comment]
Not sure if that's so simple. Mail clients are very complicated programs and that is why there is so little of them and even less those really good ones. Probably nobody would want that kind of responsibility and work on their shoulder. But... who knows? I would be glad if I have been mistaken.

**Comment by 3DJetengine** [comment]
I believe one of the main problems with 'Geary' was the lack of GPG and encryption-support, which was never figured out.
>See 'Top of the List'
https://www.bountysource.com/teams/geary/issues

**Comment by RicardoEPRodrigues** [comment]
Any news on this topic? Has it been decided what will be out future default email client?

**Comment by WatchMkr** [comment]
We have decided to use Geary for the 17.10 release. In our estimation, it's the cleanest fit into Pop and provides good functionality. We are watching development of elementary OS Mail as it looks promising. Advanced users may want Evolution or Thunderbird.

**Comment by RicardoEPRodrigues** [comment]
Will you patch it to use the Online Accounts?

**Comment by WatchMkr** [comment]
Not by release. It's a hole we'd rather not have but it's there for now.
